version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: homics-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:1.0.0
    container_name: homics-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
