INSERT INTO article (id,price, stock,  name, description, image)
VALUES(1,3, 3,'Banana', 'Amazing set of bananas, but the best is still this description.','https://staging.andros.ch/admin/wp-content/uploads/2018/03/banane.png'),
(2, 2, 1,'Carrot', 'You know what we say about the carrot: the more you eat, the kinder you become. Furthermore, it makes your ass cheeks pink. Just for that, you should buy it.','https://www.olfastory.com/sites/www.olfastory.com/files/styles/400x400/public/carotte.jpg'),
(3, 1, 14,'Leek', 'The leek is a vegetable, a cultivar of Allium ampeloprasum, the broadleaf wild leek. The edible part of the plant is a bundle of leaf sheaths that is sometimes erroneously called a stem or stalk. I bet you didn''t know that fact.','https://image.afcdn.com/recipe/20170607/67489_w300h300c1cx350cy350.jpg'),
(4, 3.50, 5,'Cabbage', 'It apparently comes from south-west of Europe. But what you really want to know is: does baby come out of cabbages?','https://static.greenweez.com/images/products/87000/600/les-paysans-bio-chou-vert-lisse-bio-1-piece.jpg'),
(5, 2.05, 0,'Eggplant', 'The best receipe out of eggplant is still the moussaka. One point for the greek.','https://cdn1.woolworths.media/content/wowproductimages/medium/137546.jpg'),
(6, 3, 5,'Onion', 'Did you know that: More than 1 000 onions varieties can be found in Europe. Crazy, right!','https://ripeme.com/wp-content/uploads/RV-10050-RIPE-ORGANIC-ORGANIC-ONION-RED.jpg'),
(7, 4, 20,'Avocado', 'Only one thing to say ... Guacamole nd Cinqo de mayo.','https://www.cleangreencafe.com/CGC/wp-content/uploads/2014/02/blog-avo.png'),
(8, 2.35, 5,'Grape', 'A grape is a fruit, botanically a berry, of the deciduous woody vines of the flowering plant genus Vitis. What will we do without it? I often asked myself.','https://az826390.vo.msecnd.net/cdn/media/home/produits_a_decouvrir/fruits_et_legumes/raisins/produits-a-decouvrir-fruits-et-legumes-raisin-bloc-red-globe-pub62350-raisin-red-globe-eau.ashx?la=fr&w=700&hash=C3CC170DB64643AD0014D06FC5C111A54D958EA3'),
(9, 2, 5,'Pitaya', 'Or well known as dragon fruit, it is kind of rare in Europe but what a divine taste. You can find a lot of it in Colombia.','https://cdn3.volusion.com/kceqm.mleru/v/vspfiles/photos/1747-2.jpg?1547804944'),
(10, 1, 5,'Turnip', 'You never know what to do with a turnip but what about a stew (or pot-au-feu) tonight?','https://www.charlet.com/wp-content/uploads/2017/10/navet-1.png');

