# Application YAML configuration

# Set port for gateway to 8080
server:
  port: 8080

spring:
  application:
    name: zuul-server

zuul:
  routes:
    monoservice:
      path: /mono/**
      url: http://localhost:8090/mono/
    useractivityservice:
      path: /user/**
      url: http://localhost:9001/user/